---
language: python
sudo: false
install:
- pip install -r requirements.txt
before_script:
- git config --global user.name Travis
- git config --global user.email travis@example.org
script:
- ansible-playbook -i 127.0.0.1, -c local -s
    -e ssh_user=travis
    -e hostname=travis-tmp-host.demo.modcloth.com
    -vvvv
    ./example.yml
